/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacaotitulo;

import javax.validation.constraints.NotNull;
import br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacao.ConciliacaoTransacaoLookupResult;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import br.com.kerubin.api.cadastros.banco.entity.planoconta.PlanoContaLookupResult;
import br.com.kerubin.api.cadastros.banco.SituacaoConciliacaoTrn;

public class ConciliacaoTransacaoTitulo {

	private java.util.UUID id;
	
	@NotNull(message="\"Transações\" é obrigatório.")
	private ConciliacaoTransacaoLookupResult conciliacaoTransacao;
	
	@NotNull(message="\"Id. título\" é obrigatório.")
	private java.util.UUID tituloConciliadoId;
	
	@NotBlank(message="\"Descrição título\" é obrigatório.")
	@Size(max = 255, message = "\"Descrição título\" pode ter no máximo 255 caracteres.")
	private String tituloConciliadoDesc;
	
	private java.math.BigDecimal tituloConciliadoValor;
	
	@NotNull(message="\"Data vencimento\" é obrigatório.")
	private java.time.LocalDate tituloConciliadoDataVen;
	
	private java.time.LocalDate tituloConciliadoDataPag;
	
	private PlanoContaLookupResult tituloPlanoContas;
	
	private java.time.LocalDate dataConciliacao;
	
	@NotNull(message="\"situacaoConciliacaoTrn\" é obrigatório.")
	private SituacaoConciliacaoTrn situacaoConciliacaoTrn;
	
	
	public ConciliacaoTransacaoTitulo() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}
	
	
	public java.util.UUID getId() {
		return id;
	}
	
	public ConciliacaoTransacaoLookupResult getConciliacaoTransacao() {
		return conciliacaoTransacao;
	}
	
	public java.util.UUID getTituloConciliadoId() {
		return tituloConciliadoId;
	}
	
	public String getTituloConciliadoDesc() {
		return tituloConciliadoDesc;
	}
	
	public java.math.BigDecimal getTituloConciliadoValor() {
		return tituloConciliadoValor;
	}
	
	public java.time.LocalDate getTituloConciliadoDataVen() {
		return tituloConciliadoDataVen;
	}
	
	public java.time.LocalDate getTituloConciliadoDataPag() {
		return tituloConciliadoDataPag;
	}
	
	public PlanoContaLookupResult getTituloPlanoContas() {
		return tituloPlanoContas;
	}
	
	public java.time.LocalDate getDataConciliacao() {
		return dataConciliacao;
	}
	
	public SituacaoConciliacaoTrn getSituacaoConciliacaoTrn() {
		return situacaoConciliacaoTrn;
	}
	
	public void setId(java.util.UUID id) {
		this.id = id;
	}
	
	public void setConciliacaoTransacao(ConciliacaoTransacaoLookupResult conciliacaoTransacao) {
		this.conciliacaoTransacao = conciliacaoTransacao;
	}
	
	public void setTituloConciliadoId(java.util.UUID tituloConciliadoId) {
		this.tituloConciliadoId = tituloConciliadoId;
	}
	
	public void setTituloConciliadoDesc(String tituloConciliadoDesc) {
		this.tituloConciliadoDesc = tituloConciliadoDesc;
	}
	
	public void setTituloConciliadoValor(java.math.BigDecimal tituloConciliadoValor) {
		this.tituloConciliadoValor = tituloConciliadoValor;
	}
	
	public void setTituloConciliadoDataVen(java.time.LocalDate tituloConciliadoDataVen) {
		this.tituloConciliadoDataVen = tituloConciliadoDataVen;
	}
	
	public void setTituloConciliadoDataPag(java.time.LocalDate tituloConciliadoDataPag) {
		this.tituloConciliadoDataPag = tituloConciliadoDataPag;
	}
	
	public void setTituloPlanoContas(PlanoContaLookupResult tituloPlanoContas) {
		this.tituloPlanoContas = tituloPlanoContas;
	}
	
	public void setDataConciliacao(java.time.LocalDate dataConciliacao) {
		this.dataConciliacao = dataConciliacao;
	}
	
	public void setSituacaoConciliacaoTrn(SituacaoConciliacaoTrn situacaoConciliacaoTrn) {
		this.situacaoConciliacaoTrn = situacaoConciliacaoTrn;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ConciliacaoTransacaoTitulo other = (ConciliacaoTransacaoTitulo) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		
		return true;
	}
	
	@Override
	public int hashCode() {
		return 31;
	}
	
	/* 
	@Override
	public String toString() {
		// Enabling toString for JPA entities will implicitly trigger lazy loading on all fields.
	}
	*/

}
