/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.contabancaria;



public interface ContaBancariaAutoComplete {

	java.util.UUID getId();
	
	String getNomeTitular();
	
	String getCpfCnpjTitular();
	
	String getNumeroConta();
	
	String getDigito();
	
	void setId(java.util.UUID id);
	
	void setNomeTitular(String nomeTitular);
	
	void setCpfCnpjTitular(String cpfCnpjTitular);
	
	void setNumeroConta(String numeroConta);
	
	void setDigito(String digito);

}
