/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacao;

import java.util.List;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import br.com.kerubin.api.cadastros.banco.entity.conciliacaobancaria.ConciliacaoBancariaAutoComplete;
import br.com.kerubin.api.cadastros.banco.entity.planoconta.PlanoContaAutoComplete;
import br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacaotitulo.ConciliacaoTransacaoTituloAutoComplete;

public interface ConciliacaoTransacaoService {
	
	public ConciliacaoTransacaoEntity create(ConciliacaoTransacaoEntity conciliacaoTransacaoEntity);
	
	public ConciliacaoTransacaoEntity read(java.util.UUID id);
	
	public ConciliacaoTransacaoEntity update(java.util.UUID id, ConciliacaoTransacaoEntity conciliacaoTransacaoEntity);
	
	public void delete(java.util.UUID id);
	
	public void deleteInBulk(java.util.List<java.util.UUID> idList);
	
	public Page<ConciliacaoTransacaoEntity> list(ConciliacaoTransacaoListFilter conciliacaoTransacaoListFilter, Pageable pageable);
	
	public Collection<ConciliacaoTransacaoAutoComplete> autoComplete(String query);
	
	// Begin relationships autoComplete 
	public Collection<ConciliacaoBancariaAutoComplete> conciliacaoBancariaConciliacaoBancariaAutoComplete(String query);
	public Collection<PlanoContaAutoComplete> planoContaTituloPlanoContasAutoComplete(String query, ConciliacaoTransacao conciliacaoTransacao);
	public Collection<ConciliacaoTransacaoTituloAutoComplete> conciliacaoTransacaoTituloConciliacaoTransacaoTitulosAutoComplete(String query);
	// End relationships autoComplete
	 
	
	public Collection<ConciliacaoTransacaoTrnHistoricoAutoComplete> conciliacaoTransacaoTrnHistoricoAutoComplete(String query);
	
	public Collection<ConciliacaoTransacaoTrnDocumentoAutoComplete> conciliacaoTransacaoTrnDocumentoAutoComplete(String query);
	// Begin findBy methods
	List<ConciliacaoTransacaoEntity> findByIdIn(List<java.util.UUID> ids);
	Collection<ConciliacaoTransacaoEntity> findConciliacaoTransacaoByConciliacaoBancaria(java.util.UUID id);
	List<ConciliacaoTransacaoEntity> findByIdIsNotAndTituloConciliadoIdIs(java.util.UUID id, java.util.UUID tituloConciliadoId);
	// End findBy methods
}
