/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacao;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class ConciliacaoTransacaoAutoCompleteImpl implements ConciliacaoTransacaoAutoComplete {

	private java.util.UUID id;
	
	private String trnId;
	
	public ConciliacaoTransacaoAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
