/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco;

public interface CadastrosBancoConstants {
	
	String DOMAIN = "cadastros";
	String SERVICE = "banco";
	
	interface Events {
		
	}

}
