/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco;


public enum SituacaoConciliacaoTrn {
	NAO_CONCILIADO,
	CONCILIAR_CONTAS_PAGAR,
	CONCILIADO_CONTAS_PAGAR,
	CONTAS_PAGAR_BAIXADO_SEM_CONCILIACAO,
	CONCILIAR_CONTAS_RECEBER,
	CONCILIADO_CONTAS_RECEBER,
	CONTAS_RECEBER_BAIXADO_SEM_CONCILIACAO,
	CONCILIAR_CAIXA,
	CONCILIADO_CAIXA,
	CAIXA_BAIXADO_SEM_CONCILIACAO,
	ERRO,
	CANCELADO;
}

