/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco;


public enum SituacaoConciliacao {
	NAO_CONCILIADO,
	ANALISANDO_TRANSACOES,
	TRANSACOES_ANALISADAS,
	CONCILIANDO_TRANSACOES,
	CONCILIADO,
	CONCILIADO_COM_ERRO,
	CANCELADO;
}

