/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.cartaocredito;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Id;
import javax.persistence.Column;
import br.com.kerubin.api.database.entity.AuditingEntity;
import javax.persistence.Transient;
import javax.persistence.GeneratedValue;
import org.hibernate.annotations.GenericGenerator;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;
import br.com.kerubin.api.cadastros.banco.entity.banco.BancoEntity;
import javax.persistence.ManyToOne;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import br.com.kerubin.api.cadastros.banco.entity.bandeiracartao.BandeiraCartaoEntity;

@Entity
@Table(name = "cartao_credito")
public class CartaoCreditoEntity extends AuditingEntity {

	@GeneratedValue(generator = "uuid2")
	@GenericGenerator(name = "uuid2", strategy = "uuid2")
	@Id
	@Column(name="id")
	private java.util.UUID id;
	
	@NotBlank(message="\"Nome do títular do cartão\" é obrigatório.")
	@Size(max = 255, message = "\"Nome do títular do cartão\" pode ter no máximo 255 caracteres.")
	@Column(name="nome_titular")
	private String nomeTitular;
	
	@NotNull(message="\"Banco\" é obrigatório.")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banco")
	private BancoEntity banco;
	
	@NotBlank(message="\"Número do cartão\" é obrigatório.")
	@Size(max = 50, message = "\"Número do cartão\" pode ter no máximo 50 caracteres.")
	@Column(name="numero_cartao")
	private String numeroCartao;
	
	@Column(name="validade")
	private java.time.LocalDate validade;
	
	@Size(max = 10, message = "\"Código de segurança\" pode ter no máximo 10 caracteres.")
	@Column(name="codigo_seguranca")
	private String codigoSeguranca;
	
	@Column(name="valor_limite")
	private java.math.BigDecimal valorLimite;
	
	@Transient
	private Boolean maisOpcoes = false;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bandeira_cartao")
	private BandeiraCartaoEntity bandeiraCartao;
	
	@NotNull(message="\"Cartão ativo\" é obrigatório.")
	@Column(name="ativo")
	private Boolean ativo = true;
	
	public java.util.UUID getId() {
		return id;
	}
	
	public String getNomeTitular() {
		return nomeTitular;
	}
	
	public BancoEntity getBanco() {
		return banco;
	}
	
	public String getNumeroCartao() {
		return numeroCartao;
	}
	
	public java.time.LocalDate getValidade() {
		return validade;
	}
	
	public String getCodigoSeguranca() {
		return codigoSeguranca;
	}
	
	public java.math.BigDecimal getValorLimite() {
		return valorLimite;
	}
	
	public Boolean getMaisOpcoes() {
		return maisOpcoes;
	}
	
	public boolean isMaisOpcoes() {
		return Boolean.TRUE.equals(maisOpcoes);
	}
	
	public BandeiraCartaoEntity getBandeiraCartao() {
		return bandeiraCartao;
	}
	
	public Boolean getAtivo() {
		return ativo;
	}
	
	public boolean isAtivo() {
		return Boolean.TRUE.equals(ativo);
	}
	
	public void setId(java.util.UUID id) {
		this.id = id;
	}
	
	public void setNomeTitular(String nomeTitular) {
		this.nomeTitular = nomeTitular != null ? nomeTitular.trim() : nomeTitular; // Chamadas REST fazem trim.
	}
	
	public void setBanco(BancoEntity banco) {
		this.banco = banco;
	}
	
	public void setNumeroCartao(String numeroCartao) {
		this.numeroCartao = numeroCartao != null ? numeroCartao.trim() : numeroCartao; // Chamadas REST fazem trim.
	}
	
	public void setValidade(java.time.LocalDate validade) {
		this.validade = validade;
	}
	
	public void setCodigoSeguranca(String codigoSeguranca) {
		this.codigoSeguranca = codigoSeguranca != null ? codigoSeguranca.trim() : codigoSeguranca; // Chamadas REST fazem trim.
	}
	
	public void setValorLimite(java.math.BigDecimal valorLimite) {
		this.valorLimite = valorLimite;
	}
	
	public void setMaisOpcoes(Boolean maisOpcoes) {
		this.maisOpcoes = maisOpcoes;
	}
	
	public void setBandeiraCartao(BandeiraCartaoEntity bandeiraCartao) {
		this.bandeiraCartao = bandeiraCartao;
	}
	
	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}
	
	public void assign(CartaoCreditoEntity source) {
		if (source != null) {
			this.setId(source.getId());
			this.setNomeTitular(source.getNomeTitular());
			this.setBanco(source.getBanco());
			this.setNumeroCartao(source.getNumeroCartao());
			this.setValidade(source.getValidade());
			this.setCodigoSeguranca(source.getCodigoSeguranca());
			this.setValorLimite(source.getValorLimite());
			this.setMaisOpcoes(source.getMaisOpcoes());
			this.setBandeiraCartao(source.getBandeiraCartao());
			this.setAtivo(source.getAtivo());
			this.setCreatedBy(source.getCreatedBy());
			this.setCreatedDate(source.getCreatedDate());
			this.setLastModifiedBy(source.getLastModifiedBy());
			this.setLastModifiedDate(source.getLastModifiedDate());
		}
	}
	
	public CartaoCreditoEntity clone() {
		return clone(new java.util.HashMap<>());
	}
	
	public CartaoCreditoEntity clone(java.util.Map<Object, Object> visited) {
		if (visited.containsKey(this)) {
			return (CartaoCreditoEntity) visited.get(this);
		}
				
		CartaoCreditoEntity theClone = new CartaoCreditoEntity();
		visited.put(this, theClone);
		
		theClone.setId(this.getId());
		theClone.setNomeTitular(this.getNomeTitular());
		theClone.setBanco(this.getBanco() != null ? this.getBanco().clone(visited) : null);
		theClone.setNumeroCartao(this.getNumeroCartao());
		theClone.setValidade(this.getValidade());
		theClone.setCodigoSeguranca(this.getCodigoSeguranca());
		theClone.setValorLimite(this.getValorLimite());
		theClone.setMaisOpcoes(this.getMaisOpcoes());
		theClone.setBandeiraCartao(this.getBandeiraCartao() != null ? this.getBandeiraCartao().clone(visited) : null);
		theClone.setAtivo(this.getAtivo());
		theClone.setCreatedBy(this.getCreatedBy());
		theClone.setCreatedDate(this.getCreatedDate());
		theClone.setLastModifiedBy(this.getLastModifiedBy());
		theClone.setLastModifiedDate(this.getLastModifiedDate());
		
		return theClone;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CartaoCreditoEntity other = (CartaoCreditoEntity) obj;
			
		
		// Field: id
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id))
			return false;
		
		// Field: nomeTitular
		if (nomeTitular == null) {
			if (other.nomeTitular != null) {
				return false;
			}
		} else if (!nomeTitular.equals(other.nomeTitular))
			return false;
		
		// Field: banco
		if (banco == null) {
			if (other.banco != null) {
				return false;
			}
		} else if (banco.getId() == null) {
			if (other.banco.getId() != null)
				return false;
		} else if (!banco.getId().equals(other.banco.getId())) 
			return false;
		
		// Field: numeroCartao
		if (numeroCartao == null) {
			if (other.numeroCartao != null) {
				return false;
			}
		} else if (!numeroCartao.equals(other.numeroCartao))
			return false;
		
		// Field: validade
		if (validade == null) {
			if (other.validade != null) {
				return false;
			}
		} else if (!validade.equals(other.validade))
			return false;
		
		// Field: codigoSeguranca
		if (codigoSeguranca == null) {
			if (other.codigoSeguranca != null) {
				return false;
			}
		} else if (!codigoSeguranca.equals(other.codigoSeguranca))
			return false;
		
		// Field: valorLimite
		if (valorLimite == null) {
			if (other.valorLimite != null) {
				return false;
			}
		} else if (!valorLimite.equals(other.valorLimite))
			return false;
		
		// Field: maisOpcoes
		if (maisOpcoes == null) {
			if (other.maisOpcoes != null) {
				return false;
			}
		} else if (!maisOpcoes.equals(other.maisOpcoes))
			return false;
		
		// Field: bandeiraCartao
		if (bandeiraCartao == null) {
			if (other.bandeiraCartao != null) {
				return false;
			}
		} else if (bandeiraCartao.getId() == null) {
			if (other.bandeiraCartao.getId() != null)
				return false;
		} else if (!bandeiraCartao.getId().equals(other.bandeiraCartao.getId())) 
			return false;
		
		// Field: ativo
		if (ativo == null) {
			if (other.ativo != null) {
				return false;
			}
		} else if (!ativo.equals(other.ativo))
			return false;
		
		// Field: createdBy
		if (createdBy == null) {
			if (other.createdBy != null) {
				return false;
			}
		} else if (!createdBy.equals(other.createdBy))
			return false;
		
		// Field: createdDate
		if (createdDate == null) {
			if (other.createdDate != null) {
				return false;
			}
		} else if (!createdDate.equals(other.createdDate))
			return false;
		
		// Field: lastModifiedBy
		if (lastModifiedBy == null) {
			if (other.lastModifiedBy != null) {
				return false;
			}
		} else if (!lastModifiedBy.equals(other.lastModifiedBy))
			return false;
		
		// Field: lastModifiedDate
		if (lastModifiedDate == null) {
			if (other.lastModifiedDate != null) {
				return false;
			}
		} else if (!lastModifiedDate.equals(other.lastModifiedDate))
			return false;
		
		return true;
	}
	
	@Override
	public int hashCode() {
		return 31;
	}
	
	/* 
	@Override
	public String toString() {
		// Enabling toString for JPA entities will implicitly trigger lazy loading on all fields.
	}
	*/

}
