/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.conciliacaobancaria;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class ConciliacaoBancariaAutoCompleteImpl implements ConciliacaoBancariaAutoComplete {

	private java.util.UUID id;
	
	private String bancoId;
	
	public ConciliacaoBancariaAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
