/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


package br.com.kerubin.api.cadastros.banco.entity.conciliacaobancaria;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import br.com.kerubin.api.servicecore.mapper.ObjectMapper;

@Component
public class ConciliacaoBancariaDTOConverter {

	@Inject
	private ObjectMapper mapper;

	public ConciliacaoBancaria convertEntityToDto(ConciliacaoBancariaEntity entity) {
		ConciliacaoBancaria dto = null;
		if (entity != null) {
			dto = mapper.map(entity, ConciliacaoBancaria.class, true); // Do not permit passwords fields go outside.
		}
		return dto;
	}


	public ConciliacaoBancariaEntity convertDtoToEntity(ConciliacaoBancaria dto) {
		ConciliacaoBancariaEntity entity = null;
		if (dto != null) {
			entity = mapper.map(dto, ConciliacaoBancariaEntity.class);
		}
		return entity;
	}


}