/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


package br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacaotitulo;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import br.com.kerubin.api.servicecore.mapper.ObjectMapper;

@Component
public class ConciliacaoTransacaoTituloDTOConverter {

	@Inject
	private ObjectMapper mapper;

	public ConciliacaoTransacaoTitulo convertEntityToDto(ConciliacaoTransacaoTituloEntity entity) {
		ConciliacaoTransacaoTitulo dto = null;
		if (entity != null) {
			dto = mapper.map(entity, ConciliacaoTransacaoTitulo.class, true); // Do not permit passwords fields go outside.
		}
		return dto;
	}


	public ConciliacaoTransacaoTituloEntity convertDtoToEntity(ConciliacaoTransacaoTitulo dto) {
		ConciliacaoTransacaoTituloEntity entity = null;
		if (dto != null) {
			entity = mapper.map(dto, ConciliacaoTransacaoTituloEntity.class);
		}
		return entity;
	}


}