/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacaotitulo;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class ConciliacaoTransacaoTituloAutoCompleteImpl implements ConciliacaoTransacaoTituloAutoComplete {

	private java.util.UUID id;
	
	private String tituloConciliadoDesc;
	
	public ConciliacaoTransacaoTituloAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
