/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacaotitulo;

import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacao.ConciliacaoTransacaoAutoComplete;
import br.com.kerubin.api.cadastros.banco.entity.planoconta.PlanoContaAutoComplete;

public interface ConciliacaoTransacaoTituloService {
	
	public ConciliacaoTransacaoTituloEntity create(ConciliacaoTransacaoTituloEntity conciliacaoTransacaoTituloEntity);
	
	public ConciliacaoTransacaoTituloEntity read(java.util.UUID id);
	
	public ConciliacaoTransacaoTituloEntity update(java.util.UUID id, ConciliacaoTransacaoTituloEntity conciliacaoTransacaoTituloEntity);
	
	public void delete(java.util.UUID id);
	
	public void deleteInBulk(java.util.List<java.util.UUID> idList);
	
	public Page<ConciliacaoTransacaoTituloEntity> list(ConciliacaoTransacaoTituloListFilter conciliacaoTransacaoTituloListFilter, Pageable pageable);
	
	public Collection<ConciliacaoTransacaoTituloAutoComplete> autoComplete(String query);
	
	// Begin relationships autoComplete 
	public Collection<ConciliacaoTransacaoAutoComplete> conciliacaoTransacaoConciliacaoTransacaoAutoComplete(String query);
	public Collection<PlanoContaAutoComplete> planoContaTituloPlanoContasAutoComplete(String query);
	// End relationships autoComplete
	 
}
