/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.conciliacaotransacaotitulo;

import com.querydsl.core.types.Predicate;

public interface ConciliacaoTransacaoTituloListFilterPredicate {
	
	Predicate mountAndGetPredicate(ConciliacaoTransacaoTituloListFilter conciliacaoTransacaoTituloListFilter);

}

