/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.banco.entity.contabancaria;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Id;
import javax.persistence.Column;
import br.com.kerubin.api.database.entity.AuditingEntity;
import javax.persistence.Transient;
import javax.persistence.GeneratedValue;
import org.hibernate.annotations.GenericGenerator;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import br.com.kerubin.api.servicecore.validator.constraint.CpfOrCnpj;
import javax.validation.constraints.NotNull;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import br.com.kerubin.api.cadastros.banco.TipoContaBancaria;
import br.com.kerubin.api.cadastros.banco.entity.agenciabancaria.AgenciaBancariaEntity;
import javax.persistence.ManyToOne;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import br.com.kerubin.api.cadastros.banco.entity.bandeiracartao.BandeiraCartaoEntity;

@Entity
@Table(name = "conta_bancaria")
public class ContaBancariaEntity extends AuditingEntity {

	@GeneratedValue(generator = "uuid2")
	@GenericGenerator(name = "uuid2", strategy = "uuid2")
	@Id
	@Column(name="id")
	private java.util.UUID id;
	
	@NotBlank(message="\"Nome do títular da conta\" é obrigatório.")
	@Size(max = 255, message = "\"Nome do títular da conta\" pode ter no máximo 255 caracteres.")
	@Column(name="nome_titular")
	private String nomeTitular;
	
	@Size(max = 20, message = "\"CPF/CNPJ do títular da conta\" pode ter no máximo 20 caracteres.")
	@CpfOrCnpj(message="CPF/CNPJ inválido.")
	@Column(name="cpf_cnpj_titular")
	private String cpfCnpjTitular;
	
	@NotNull(message="\"Tipo da conta\" é obrigatório.")
	@Enumerated(EnumType.STRING)
	@Column(name="tipo_conta_bancaria")
	private TipoContaBancaria tipoContaBancaria;
	
	@NotNull(message="\"Agência bancária\" é obrigatório.")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agencia")
	private AgenciaBancariaEntity agencia;
	
	@NotBlank(message="\"Número da conta\" é obrigatório.")
	@Size(max = 30, message = "\"Número da conta\" pode ter no máximo 30 caracteres.")
	@Column(name="numero_conta")
	private String numeroConta;
	
	@Size(max = 10, message = "\"Dígito\" pode ter no máximo 10 caracteres.")
	@Column(name="digito")
	private String digito;
	
	@Column(name="saldo")
	private java.math.BigDecimal saldo;
	
	@Transient
	private Boolean maisOpcoes = false;
	
	@NotNull(message="\"Conta ativa\" é obrigatório.")
	@Column(name="ativo")
	private Boolean ativo = true;
	
	@Column(name="data_validade")
	private java.time.LocalDate dataValidade;
	
	@Size(max = 50, message = "\"Número do cartão\" pode ter no máximo 50 caracteres.")
	@Column(name="numero_cartao")
	private String numeroCartao;
	
	@Size(max = 10, message = "\"Código de segurança\" pode ter no máximo 10 caracteres.")
	@Column(name="codigo_seguranca")
	private String codigoSeguranca;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bandeira_cartao")
	private BandeiraCartaoEntity bandeiraCartao;
	
	public java.util.UUID getId() {
		return id;
	}
	
	public String getNomeTitular() {
		return nomeTitular;
	}
	
	public String getCpfCnpjTitular() {
		return cpfCnpjTitular;
	}
	
	public TipoContaBancaria getTipoContaBancaria() {
		return tipoContaBancaria;
	}
	
	public AgenciaBancariaEntity getAgencia() {
		return agencia;
	}
	
	public String getNumeroConta() {
		return numeroConta;
	}
	
	public String getDigito() {
		return digito;
	}
	
	public java.math.BigDecimal getSaldo() {
		return saldo;
	}
	
	public Boolean getMaisOpcoes() {
		return maisOpcoes;
	}
	
	public boolean isMaisOpcoes() {
		return Boolean.TRUE.equals(maisOpcoes);
	}
	
	public Boolean getAtivo() {
		return ativo;
	}
	
	public boolean isAtivo() {
		return Boolean.TRUE.equals(ativo);
	}
	
	public java.time.LocalDate getDataValidade() {
		return dataValidade;
	}
	
	public String getNumeroCartao() {
		return numeroCartao;
	}
	
	public String getCodigoSeguranca() {
		return codigoSeguranca;
	}
	
	public BandeiraCartaoEntity getBandeiraCartao() {
		return bandeiraCartao;
	}
	
	public void setId(java.util.UUID id) {
		this.id = id;
	}
	
	public void setNomeTitular(String nomeTitular) {
		this.nomeTitular = nomeTitular != null ? nomeTitular.trim() : nomeTitular; // Chamadas REST fazem trim.
	}
	
	public void setCpfCnpjTitular(String cpfCnpjTitular) {
		this.cpfCnpjTitular = cpfCnpjTitular != null ? cpfCnpjTitular.trim() : cpfCnpjTitular; // Chamadas REST fazem trim.
	}
	
	public void setTipoContaBancaria(TipoContaBancaria tipoContaBancaria) {
		this.tipoContaBancaria = tipoContaBancaria;
	}
	
	public void setAgencia(AgenciaBancariaEntity agencia) {
		this.agencia = agencia;
	}
	
	public void setNumeroConta(String numeroConta) {
		this.numeroConta = numeroConta != null ? numeroConta.trim() : numeroConta; // Chamadas REST fazem trim.
	}
	
	public void setDigito(String digito) {
		this.digito = digito != null ? digito.trim() : digito; // Chamadas REST fazem trim.
	}
	
	public void setSaldo(java.math.BigDecimal saldo) {
		this.saldo = saldo;
	}
	
	public void setMaisOpcoes(Boolean maisOpcoes) {
		this.maisOpcoes = maisOpcoes;
	}
	
	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}
	
	public void setDataValidade(java.time.LocalDate dataValidade) {
		this.dataValidade = dataValidade;
	}
	
	public void setNumeroCartao(String numeroCartao) {
		this.numeroCartao = numeroCartao != null ? numeroCartao.trim() : numeroCartao; // Chamadas REST fazem trim.
	}
	
	public void setCodigoSeguranca(String codigoSeguranca) {
		this.codigoSeguranca = codigoSeguranca != null ? codigoSeguranca.trim() : codigoSeguranca; // Chamadas REST fazem trim.
	}
	
	public void setBandeiraCartao(BandeiraCartaoEntity bandeiraCartao) {
		this.bandeiraCartao = bandeiraCartao;
	}
	
	public void assign(ContaBancariaEntity source) {
		if (source != null) {
			this.setId(source.getId());
			this.setNomeTitular(source.getNomeTitular());
			this.setCpfCnpjTitular(source.getCpfCnpjTitular());
			this.setTipoContaBancaria(source.getTipoContaBancaria());
			this.setAgencia(source.getAgencia());
			this.setNumeroConta(source.getNumeroConta());
			this.setDigito(source.getDigito());
			this.setSaldo(source.getSaldo());
			this.setMaisOpcoes(source.getMaisOpcoes());
			this.setAtivo(source.getAtivo());
			this.setDataValidade(source.getDataValidade());
			this.setNumeroCartao(source.getNumeroCartao());
			this.setCodigoSeguranca(source.getCodigoSeguranca());
			this.setBandeiraCartao(source.getBandeiraCartao());
			this.setCreatedBy(source.getCreatedBy());
			this.setCreatedDate(source.getCreatedDate());
			this.setLastModifiedBy(source.getLastModifiedBy());
			this.setLastModifiedDate(source.getLastModifiedDate());
		}
	}
	
	public ContaBancariaEntity clone() {
		return clone(new java.util.HashMap<>());
	}
	
	public ContaBancariaEntity clone(java.util.Map<Object, Object> visited) {
		if (visited.containsKey(this)) {
			return (ContaBancariaEntity) visited.get(this);
		}
				
		ContaBancariaEntity theClone = new ContaBancariaEntity();
		visited.put(this, theClone);
		
		theClone.setId(this.getId());
		theClone.setNomeTitular(this.getNomeTitular());
		theClone.setCpfCnpjTitular(this.getCpfCnpjTitular());
		theClone.setTipoContaBancaria(this.getTipoContaBancaria());
		theClone.setAgencia(this.getAgencia() != null ? this.getAgencia().clone(visited) : null);
		theClone.setNumeroConta(this.getNumeroConta());
		theClone.setDigito(this.getDigito());
		theClone.setSaldo(this.getSaldo());
		theClone.setMaisOpcoes(this.getMaisOpcoes());
		theClone.setAtivo(this.getAtivo());
		theClone.setDataValidade(this.getDataValidade());
		theClone.setNumeroCartao(this.getNumeroCartao());
		theClone.setCodigoSeguranca(this.getCodigoSeguranca());
		theClone.setBandeiraCartao(this.getBandeiraCartao() != null ? this.getBandeiraCartao().clone(visited) : null);
		theClone.setCreatedBy(this.getCreatedBy());
		theClone.setCreatedDate(this.getCreatedDate());
		theClone.setLastModifiedBy(this.getLastModifiedBy());
		theClone.setLastModifiedDate(this.getLastModifiedDate());
		
		return theClone;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ContaBancariaEntity other = (ContaBancariaEntity) obj;
			
		
		// Field: id
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id))
			return false;
		
		// Field: nomeTitular
		if (nomeTitular == null) {
			if (other.nomeTitular != null) {
				return false;
			}
		} else if (!nomeTitular.equals(other.nomeTitular))
			return false;
		
		// Field: cpfCnpjTitular
		if (cpfCnpjTitular == null) {
			if (other.cpfCnpjTitular != null) {
				return false;
			}
		} else if (!cpfCnpjTitular.equals(other.cpfCnpjTitular))
			return false;
		
		// Field: tipoContaBancaria
		if (tipoContaBancaria == null) {
			if (other.tipoContaBancaria != null) {
				return false;
			}
		} else if (!tipoContaBancaria.equals(other.tipoContaBancaria))
			return false;
		
		// Field: agencia
		if (agencia == null) {
			if (other.agencia != null) {
				return false;
			}
		} else if (agencia.getId() == null) {
			if (other.agencia.getId() != null)
				return false;
		} else if (!agencia.getId().equals(other.agencia.getId())) 
			return false;
		
		// Field: numeroConta
		if (numeroConta == null) {
			if (other.numeroConta != null) {
				return false;
			}
		} else if (!numeroConta.equals(other.numeroConta))
			return false;
		
		// Field: digito
		if (digito == null) {
			if (other.digito != null) {
				return false;
			}
		} else if (!digito.equals(other.digito))
			return false;
		
		// Field: saldo
		if (saldo == null) {
			if (other.saldo != null) {
				return false;
			}
		} else if (!saldo.equals(other.saldo))
			return false;
		
		// Field: maisOpcoes
		if (maisOpcoes == null) {
			if (other.maisOpcoes != null) {
				return false;
			}
		} else if (!maisOpcoes.equals(other.maisOpcoes))
			return false;
		
		// Field: ativo
		if (ativo == null) {
			if (other.ativo != null) {
				return false;
			}
		} else if (!ativo.equals(other.ativo))
			return false;
		
		// Field: dataValidade
		if (dataValidade == null) {
			if (other.dataValidade != null) {
				return false;
			}
		} else if (!dataValidade.equals(other.dataValidade))
			return false;
		
		// Field: numeroCartao
		if (numeroCartao == null) {
			if (other.numeroCartao != null) {
				return false;
			}
		} else if (!numeroCartao.equals(other.numeroCartao))
			return false;
		
		// Field: codigoSeguranca
		if (codigoSeguranca == null) {
			if (other.codigoSeguranca != null) {
				return false;
			}
		} else if (!codigoSeguranca.equals(other.codigoSeguranca))
			return false;
		
		// Field: bandeiraCartao
		if (bandeiraCartao == null) {
			if (other.bandeiraCartao != null) {
				return false;
			}
		} else if (bandeiraCartao.getId() == null) {
			if (other.bandeiraCartao.getId() != null)
				return false;
		} else if (!bandeiraCartao.getId().equals(other.bandeiraCartao.getId())) 
			return false;
		
		// Field: createdBy
		if (createdBy == null) {
			if (other.createdBy != null) {
				return false;
			}
		} else if (!createdBy.equals(other.createdBy))
			return false;
		
		// Field: createdDate
		if (createdDate == null) {
			if (other.createdDate != null) {
				return false;
			}
		} else if (!createdDate.equals(other.createdDate))
			return false;
		
		// Field: lastModifiedBy
		if (lastModifiedBy == null) {
			if (other.lastModifiedBy != null) {
				return false;
			}
		} else if (!lastModifiedBy.equals(other.lastModifiedBy))
			return false;
		
		// Field: lastModifiedDate
		if (lastModifiedDate == null) {
			if (other.lastModifiedDate != null) {
				return false;
			}
		} else if (!lastModifiedDate.equals(other.lastModifiedDate))
			return false;
		
		return true;
	}
	
	@Override
	public int hashCode() {
		return 31;
	}
	
	/* 
	@Override
	public String toString() {
		// Enabling toString for JPA entities will implicitly trigger lazy loading on all fields.
	}
	*/

}
